--> STARTING SERVER 
SET SERVEROUTPUT ON ; 

DECLARE
-- ALL THE VARIABLES DECLARATION 

N1 NUMBER(3); 
N2 NUMBER(3); 
BEGIN
-- USE ALL VARIABLES

N1 := &N1 ; --TAKING INPUT IN N1 
N2 := &N2; --TAKING INPUT IN N2 

IF N1>N2 THEN
    DBMS_OUTPUT.PUT_LINE(N1 || ' IS GREATER') ; 
ELSE 
    DBMS_OUTPUT.PUT_LINE(N2 || ' IS GREATER') ; 
END IF;

END;
/