DROP SEQUENCE TEST_SQ ;
create sequence TEST_SQ increment by 1 start with 100 MINVALUE 10 MAXVALUE 102 CYCLE; 

SELECT TEST_SQ.NEXTVAL FROM DUAL ;

--> CONCATINATION
SELECT 'H' || TEST_SQ.NEXTVAL FROM DUAL ;

--> SELECT TEST_SQ.CURRVAL FROM DUAL ; 

--> ALTER 
ALTER SEQUENCE TEST_SQ increment BY 2 ; 

SELECT TEST_SQ.NEXTVAL FROM DUAL ;
SELECT TEST_SQ.NEXTVAL FROM DUAL ;