DROP TABLE TEST29 ; 
CREATE TABLE TEST29(
    ID NUMBER(2) ,
    NAME VARCHAR2(10)
);

INSERT INTO TEST29 VALUES (10 , 'AAA');
INSERT INTO TEST29 VALUES (10 , 'AAA');
INSERT INTO TEST29 VALUES (10 , 'AAA');
INSERT INTO TEST29 VALUES (20 , 'BBB');
INSERT INTO TEST29 VALUES (20 , 'BBB');
INSERT INTO TEST29 VALUES (20 , 'BBB');

SELECT * FROM TEST29; 

COMMIT ; 

SELECT ROWID , ID , NAME FROM TEST29 ;

SELECT MIN(ROWID) FROM TEST29 GROUP BY ID , NAME ; 

SELECT MIN(ROWID) ID , NAME FROM TEST29 GROUP BY ID , NAME ; 

DELETE FROM TEST29 WHERE ROWID NOT IN (SELECT MIN(ROWID) NAME FROM TEST29 GROUP BY ID , NAME ) ; 

SELECT * FROM TEST29;

ROLLBACK ; 

--ROWNUM ---->

SELECT ROWNUM , ID , NAME FROM TEST29 ; 

DELETE FROM TEST29 WHERE ROWNUM < 5 ;

SELECT * FROM TEST29 ;